const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');

const helperFn = `
function getTechStackBadges(files: Array<{ name: string; path: string; content: string; language: string }>): string[] {
  const badges: string[] = [];
  const allContent = files.map(f => f.content).join('\\n');
  const hasCompose = files.some(f => f.content.includes('androidx.compose') || f.name.includes('MainActivity.kt'));
  const hasXML = files.some(f => f.name.includes('.xml') && f.path.includes('layout'));
  const hasKotlin = files.some(f => f.language === 'kotlin' || f.name.endsWith('.kt'));
  const hasJava = files.some(f => f.language === 'java' || f.name.endsWith('.java'));
  const hasGradle = files.some(f => f.name.includes('build.gradle'));

  if (hasKotlin) {
    badges.push('![Kotlin](https://img.shields.io/badge/kotlin-%237F52FF.svg?style=for-the-badge&logo=kotlin&logoColor=white)');
  }
  if (hasJava) {
    badges.push('![Java](https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=openjdk&logoColor=white)');
  }
  if (hasCompose) {
    badges.push('![Jetpack Compose](https://img.shields.io/badge/Jetpack%20Compose-4285F4?style=for-the-badge&logo=android&logoColor=white)');
  }
  if (hasXML && !hasCompose) {
    badges.push('![Android XML](https://img.shields.io/badge/XML-Android-3DDC84?style=for-the-badge&logo=android&logoColor=white)');
  }
  if (hasGradle) {
    badges.push('![Gradle](https://img.shields.io/badge/Gradle-02303A.svg?style=for-the-badge&logo=Gradle&logoColor=white)');
  }

  if (allContent.includes('firebase')) {
    badges.push('![Firebase](https://img.shields.io/badge/firebase-%23039BE5.svg?style=for-the-badge&logo=firebase)');
  }
  if (allContent.includes('room')) {
    badges.push('![Room](https://img.shields.io/badge/Room-Database-4285F4?style=for-the-badge&logo=sqlite&logoColor=white)');
  }
  if (allContent.includes('hilt') || allContent.includes('dagger')) {
    badges.push('![Hilt](https://img.shields.io/badge/Hilt-DI-3DDC84?style=for-the-badge&logo=android&logoColor=white)');
  }
  if (allContent.includes('retrofit') || allContent.includes('okhttp')) {
    badges.push('![Retrofit](https://img.shields.io/badge/Retrofit-Network-161B22?style=for-the-badge&logo=github&logoColor=white)');
  }
  if (allContent.includes('play-services-maps') || allContent.includes('google-maps')) {
     badges.push('![Google Maps](https://img.shields.io/badge/Google%20Maps-4285F4?style=for-the-badge&logo=googlemaps&logoColor=white)');
  }
  return badges;
}
`;

if (!code.includes('getTechStackBadges')) {
  code = code.replace(
    `async function scoreAppHelper(code: string, prompt: string): Promise<number> {`,
    `${helperFn}\n\nasync function scoreAppHelper(code: string, prompt: string): Promise<number> {`
  );
}

// In generate-project
const readmeGenFiles = `
  const badges = getTechStackBadges(generatedFiles);
  generatedFiles.push({
    name: 'README.md',
    path: 'README.md',
    content: \`# Android App\\n\\nGenerated by DroidCraft IDE.\\n\\n### Tech Stack\\n\${badges.join(' ')}\\n\\n### Building\\nThis project uses GitHub actions to automatically build the APK.\`,
    language: 'markdown'
  });
`;

if (!code.includes(`name: 'README.md',`) && !code.includes(`path: 'README.md'`)) {
  code = code.replace(
    `  res.json({\n    success: true,\n    files: generatedFiles\n  });`,
    `${readmeGenFiles}\n  res.json({\n    success: true,\n    files: generatedFiles\n  });`
  );
}

// In runJob
const readmeRunJob = `
    const badges = getTechStackBadges(files);
    files.push({
      name: 'README.md',
      path: 'README.md',
      content: \`# Android App\\n\\nGenerated by DroidCraft IDE.\\n\\n### Tech Stack\\n\${badges.join(' ')}\\n\\n### Building\\nThis project uses GitHub actions to automatically build the APK.\`,
      language: 'markdown'
    });
`;

if (!code.includes(`path: 'README.md'`)) {
  code = code.replace(
    `    job.logs.push(\`✓ Complete Android Project structure generated!\`);`,
    `${readmeRunJob}\n    job.logs.push(\`✓ Complete Android Project structure generated!\`);`
  );
}

fs.writeFileSync('server.ts', code);
