import React, { useState, useEffect } from 'react';
import {
  X, Sparkles, Github, Terminal, Copy, Check, Download,
  Eye, Code, Sliders, LayoutGrid, FileText, BadgeCheck,
  Cpu, Zap, RefreshCw, AlertCircle, Save
} from 'lucide-react';
import { FileItem } from '../types';

interface Props {
  isDark: boolean;
  onClose: () => void;
  files: FileItem[];
  activeFileContent?: string;
  triggerToast: (msg: string) => void;
  onSaveReadme: (content: string) => void;
}

export default function GitHubMetadataEngineDialog({
  isDark,
  onClose,
  files,
  activeFileContent,
  triggerToast,
  onSaveReadme
}: Props) {
  const [activeTab, setActiveTab] = useState<'generate' | 'edit' | 'preview' | 'badges'>('generate');
  const [appName, setAppName] = useState('MyCyberBrutalistApp');
  const [description, setDescription] = useState('An ultra-high contrast, cyber-brutalist mobile experience driven by MandelaCore and MatrixCore pipelines.');
  const [selectedLicense, setSelectedLicense] = useState('MIT');
  const [selectedBadges, setSelectedBadges] = useState<string[]>(['build', 'license', 'kotlin', 'cyber']);
  const [readmeContent, setReadmeContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const availableBadges = [
    { id: 'build', label: 'Build: Passing', url: 'https://img.shields.io/badge/build-passing-brightgreen?style=for-the-badge&logo=github' },
    { id: 'license', label: 'License: MIT', url: 'https://img.shields.io/badge/license-MIT-blue?style=for-the-badge' },
    { id: 'kotlin', label: 'Kotlin: 2.0', url: 'https://img.shields.io/badge/Kotlin-2.0-purple?style=for-the-badge&logo=kotlin' },
    { id: 'cyber', label: 'Theme: Cyber-Brutalist', url: 'https://img.shields.io/badge/Theme-Cyber--Brutalist-yellow?style=for-the-badge&logo=matrix' },
    { id: 'security', label: 'Security: Zero Trust', url: 'https://img.shields.io/badge/Security-Zero%20Trust-red?style=for-the-badge' },
    { id: 'engine', label: 'Engine: MandelaCore', url: 'https://img.shields.io/badge/Engine-MandelaCore-cyan?style=for-the-badge' }
  ];

  const handleGenerateReadme = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const badgeMks = selectedBadges
        .map(b => availableBadges.find(x => x.id === b))
        .filter(Boolean)
        .map(b => `![${b!.label}](${b!.url})`)
        .join(' ');

      const filesList = files.map(f => `- \`${f.path}\` (${f.language || 'text'})`).join('\n');

      const markdown = `# 🌌 ${appName}

${badgeMks}

## ⚡ Description
${description}

---

## 🛠️ Cybernetic System Modules (Workspace Files)
The codebase has been programmatically compiled and audited with the following layout structure:
\`\`\`text
/root
${files.map(f => `  ├── ${f.path}`).join('\n')}
\`\`\`

### File Index Details:
${filesList}

---

## 🧩 Architecture Pipelines
- **MandelaCore**: Controls reality-shifting user interfaces, glitch transitions, and cyber-brutalist view state synchronization.
- **MatrixCore**: Validates and drives low-level transaction consensus and strict repository data flows.
- **Devator Mutation Engine**: Authorizes configs, UI themes, and layout mutations within strict consensus thresholds.

## 🚀 Getting Started

### Prerequisites
- JDK 17
- Android SDK Platform 34

### Compilation
\`\`\`bash
./gradlew assembleDebug --no-daemon
\`\`\`

## 📜 License
This project is licensed under the **${selectedLicense}** License.

---
*Generated by the GitHub Metadata Engine - Devator Consensus Sub-System.*
`;
      setReadmeContent(markdown);
      setIsGenerating(false);
      triggerToast('✓ README.md content generated successfully!');
      setActiveTab('edit');
    }, 800);
  };

  useEffect(() => {
    // Attempt to parse app name or description from files if possible
    const buildGradle = files.find(f => f.name.includes('build.gradle'));
    if (buildGradle && buildGradle.content) {
      const match = buildGradle.content.match(/namespace\s*=\s*['"](.*)['"]/);
      if (match && match[1]) {
        setAppName(match[1].split('.').pop() || 'CyberApp');
      }
    }
  }, [files]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className={`w-full max-w-4xl h-[85vh] flex flex-col border-4 ${isDark ? 'border-[#ff0055] bg-black text-white' : 'border-black bg-white text-black'} shadow-[8px_8px_0px_#000000] font-mono overflow-hidden`}>
        
        {/* Header */}
        <div className={`flex items-center justify-between p-4 border-b-4 ${isDark ? 'border-[#ff0055] bg-[#ff0055]/10' : 'border-black bg-black/5'}`}>
          <div className="flex items-center space-x-3">
            <Github className="w-6 h-6 animate-pulse" />
            <span className="text-lg font-black tracking-widest uppercase">
              GITHUB METADATA ENGINE // V1.0
            </span>
          </div>
          <button 
            onClick={onClose}
            className={`p-1 border-2 transition-all ${isDark ? 'border-[#ff0055] hover:bg-[#ff0055] hover:text-black' : 'border-black hover:bg-black hover:text-white'}`}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Navigation Tabs */}
        <div className="flex border-b-2 border-dashed border-zinc-500 bg-zinc-900/10 p-2 overflow-x-auto gap-2">
          {[
            { id: 'generate', label: '1. Generator Config', icon: Sliders },
            { id: 'badges', label: '2. Badges & Metadata', icon: BadgeCheck },
            { id: 'edit', label: '3. README Editor', icon: Code },
            { id: 'preview', label: '4. Live Preview', icon: Eye }
          ].map(tab => {
            const Icon = tab.icon;
            const active = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center space-x-2 px-3 py-1.5 border-2 text-xs font-bold transition-all ${
                  active
                    ? isDark 
                      ? 'bg-[#ff0055] text-black border-white shadow-[2px_2px_0px_white]' 
                      : 'bg-black text-white border-black shadow-[2px_2px_0px_#ff0055]'
                    : isDark
                      ? 'border-zinc-700 hover:border-zinc-500 text-zinc-400'
                      : 'border-zinc-300 hover:border-zinc-500 text-zinc-600'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-6">
          {activeTab === 'generate' && (
            <div className="space-y-6">
              <div className="p-4 border-2 border-dashed border-zinc-500 bg-zinc-500/5">
                <h3 className="text-sm font-black flex items-center space-x-2 mb-2 text-[#ff0055]">
                  <Cpu className="w-4 h-4" />
                  <span>AUTONOMOUS DOCUMENTATION PROTOCOL</span>
                </h3>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  The Devator metadata generator parses your workspace file tree, detects build scripts, namespaces, and components, and transforms them into an optimized cyber-brutalist README document suitable for cosmic portfolio deployments.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-xs font-black uppercase text-zinc-400">Application Title</label>
                  <input
                    type="text"
                    value={appName}
                    onChange={(e) => setAppName(e.target.value)}
                    className={`w-full p-2 border-2 outline-none font-bold text-sm ${isDark ? 'bg-zinc-950 border-zinc-700 text-white focus:border-[#ff0055]' : 'bg-zinc-50 border-zinc-300 text-black focus:border-black'}`}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-black uppercase text-zinc-400">Project License</label>
                  <select
                    value={selectedLicense}
                    onChange={(e) => setSelectedLicense(e.target.value)}
                    className={`w-full p-2 border-2 outline-none font-bold text-sm ${isDark ? 'bg-zinc-950 border-zinc-700 text-white focus:border-[#ff0055]' : 'bg-zinc-50 border-zinc-300 text-black focus:border-black'}`}
                  >
                    <option value="MIT">MIT License</option>
                    <option value="Apache-2.0">Apache 2.0</option>
                    <option value="GPL-3.0">GNU GPLv3</option>
                    <option value="Unlicense">Unlicense</option>
                  </select>
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-black uppercase text-zinc-400">Cybernetic Project Description</label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={4}
                  className={`w-full p-2 border-2 outline-none font-bold text-sm ${isDark ? 'bg-zinc-950 border-zinc-700 text-white focus:border-[#ff0055]' : 'bg-zinc-50 border-zinc-300 text-black focus:border-black'}`}
                />
              </div>

              <button
                onClick={handleGenerateReadme}
                className={`w-full py-3 flex items-center justify-center space-x-2 text-sm font-black uppercase tracking-widest border-2 transition-all ${
                  isDark 
                    ? 'bg-white text-black border-white hover:bg-[#ff0055] hover:text-white hover:border-[#ff0055] shadow-[4px_4px_0px_#ff0055]' 
                    : 'bg-black text-white border-black hover:bg-[#ff0055] hover:text-white hover:border-[#ff0055] shadow-[4px_4px_0px_black]'
                }`}
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="w-5 h-5 animate-spin" />
                    <span>MUTATING MATRIX BLUEPRINT...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5 animate-bounce" />
                    <span>GENERATE GITHUB README CONTENT</span>
                  </>
                )}
              </button>
            </div>
          )}

          {activeTab === 'badges' && (
            <div className="space-y-6">
              <div className="p-4 border-2 border-dashed border-zinc-500 bg-zinc-500/5">
                <h3 className="text-sm font-black text-[#ff0055] mb-2 uppercase">CHIP EMBEDDING & COSMIC SHIELDS</h3>
                <p className="text-xs text-zinc-400">
                  Select which vector metadata badges to inject into the header of your repository. These dynamically report reality status and core version protocols to outside auditors.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {availableBadges.map(badge => {
                  const selected = selectedBadges.includes(badge.id);
                  return (
                    <button
                      key={badge.id}
                      onClick={() => {
                        if (selected) {
                          setSelectedBadges(prev => prev.filter(id => id !== badge.id));
                        } else {
                          setSelectedBadges(prev => [...prev, badge.id]);
                        }
                      }}
                      className={`p-3 border-2 flex items-center justify-between text-left transition-all ${
                        selected 
                          ? isDark ? 'border-[#ff0055] bg-[#ff0055]/10' : 'border-black bg-zinc-100'
                          : isDark ? 'border-zinc-800 bg-black' : 'border-zinc-200 bg-white'
                      }`}
                    >
                      <div className="space-y-1">
                        <span className="text-xs font-bold uppercase">{badge.label}</span>
                        <img src={badge.url} alt={badge.label} className="h-5 object-contain" referrerPolicy="no-referrer" />
                      </div>
                      <div className={`w-5 h-5 border-2 flex items-center justify-center ${selected ? 'border-[#ff0055] bg-[#ff0055] text-black' : 'border-zinc-500'}`}>
                        {selected && <Check className="w-4 h-4 stroke-[3px]" />}
                      </div>
                    </button>
                  );
                })}
              </div>

              <button
                onClick={() => {
                  handleGenerateReadme();
                }}
                className={`w-full py-3 flex items-center justify-center space-x-2 text-sm font-black uppercase tracking-widest border-2 transition-all ${
                  isDark 
                    ? 'bg-[#ff0055] text-black border-white hover:bg-black hover:text-white hover:border-[#ff0055] shadow-[4px_4px_0px_white]' 
                    : 'bg-black text-white border-black hover:bg-[#ff0055] hover:border-black shadow-[4px_4px_0px_#ff0055]'
                }`}
              >
                <span>APPLY BADGES & RE-GENERATE</span>
              </button>
            </div>
          )}

          {activeTab === 'edit' && (
            <div className="h-full flex flex-col space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-xs font-black uppercase text-zinc-400">README.md Markdown Output</span>
                <span className="text-xs text-zinc-500">{readmeContent.length} chars</span>
              </div>
              <textarea
                value={readmeContent}
                onChange={(e) => setReadmeContent(e.target.value)}
                className={`w-full flex-1 min-h-[300px] p-4 border-2 font-mono text-xs outline-none focus:border-[#ff0055] ${isDark ? 'bg-zinc-950 border-zinc-800 text-[#00ffcc]' : 'bg-zinc-50 border-zinc-200 text-black'}`}
                placeholder="# Your Cyber README starts here..."
              />
            </div>
          )}

          {activeTab === 'preview' && (
            <div className="space-y-4">
              <div className="p-4 border-2 border-dashed border-zinc-500 bg-zinc-500/5">
                <span className="text-xs font-black uppercase text-zinc-400">SIMULATED PORTAL RENDER</span>
              </div>
              <div className={`p-6 border-2 rounded-lg font-sans overflow-auto max-h-[350px] ${isDark ? 'bg-zinc-900 border-zinc-800 text-zinc-100' : 'bg-zinc-50 border-zinc-200 text-zinc-900'}`}>
                {readmeContent ? (
                  <div className="prose prose-sm dark:prose-invert max-w-none space-y-4">
                    <h1 className="text-2xl font-black border-b pb-2 mb-4 flex items-center gap-2">
                      🌌 {appName}
                    </h1>
                    <div className="flex flex-wrap gap-2 mb-4">
                      {selectedBadges.map(b => {
                        const badge = availableBadges.find(x => x.id === b);
                        return badge ? <img key={b} src={badge.url} alt={badge.label} className="h-6 object-contain" referrerPolicy="no-referrer" /> : null;
                      })}
                    </div>
                    <p className="italic text-zinc-400">{description}</p>
                    <h3 className="text-lg font-bold border-b pb-1 mt-6">Cybernetic System Modules</h3>
                    <pre className="p-3 bg-black text-[#00ff00] text-xs font-mono rounded">
                      {files.map(f => `├── ${f.path}`).join('\n')}
                    </pre>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center py-12 text-center text-zinc-500">
                    <AlertCircle className="w-12 h-12 mb-2 stroke-1 text-[#ff0055]" />
                    <span className="text-sm font-bold">NO README GENERATED YET</span>
                    <span className="text-xs">Go to the Generator tab to output a markdown core.</span>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Footer actions */}
        <div className={`p-4 border-t-4 flex flex-col md:flex-row items-center justify-between gap-4 ${isDark ? 'border-[#ff0055] bg-zinc-950' : 'border-black bg-zinc-50'}`}>
          <div className="flex items-center space-x-2 text-xs text-zinc-500 font-bold">
            <BadgeCheck className="w-4 h-4 text-[#00ffcc]" />
            <span>DEVATOR MUTATION PIPELINE READY</span>
          </div>

          <div className="flex items-center space-x-3 w-full md:w-auto">
            <button
              onClick={onClose}
              className={`flex-1 md:flex-none px-6 py-2 text-xs font-black uppercase border-2 transition-all ${isDark ? 'border-zinc-700 hover:bg-zinc-800 text-zinc-400' : 'border-zinc-300 hover:bg-zinc-100 text-zinc-600'}`}
            >
              Cancel
            </button>
            <button
              onClick={() => {
                if (!readmeContent) {
                  triggerToast('⚠️ Please generate or write some content first!');
                  return;
                }
                onSaveReadme(readmeContent);
                onClose();
              }}
              className={`flex-1 md:flex-none px-6 py-2 text-xs font-black uppercase tracking-wider flex items-center justify-center space-x-2 border-2 transition-all ${
                isDark 
                  ? 'bg-[#00ffcc] text-black border-white hover:bg-black hover:text-[#00ffcc] hover:border-[#00ffcc]' 
                  : 'bg-black text-white border-black hover:bg-zinc-800'
              }`}
            >
              <Save className="w-4 h-4" />
              <span>SAVE README.MD</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
